FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /quasar-lrs

# copy both 'package.json' and 'package-lock.json' (if available)
COPY . /

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# build app for production with minification
# install project dependencies
RUN npm install
RUn npm install -g quasar-cli

EXPOSE 8080
CMD [ "quasar", "dev", "-m", "pwa" ]